/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js. It is checked in here so a fresh clone has
// the expected TypeScript ambient declarations before the first dev run.
